import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Krisztian Vegh</title>
        <meta
          name="description"
          content="Krisztian Vegh: Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Krisztián Végh</h1>

        <p className={styles.description}>Software Engineer</p>
        <div className={styles.icons}>
          <a href="https://github.com/krisvegh" target="_blank">
            <div className={`${styles.icon} ${styles.github}`}></div>
          </a>
          <a
            href="https://www.linkedin.com/in/krisztian-vegh-7411b17b/"
            target="_blank"
          >
            <div className={`${styles.icon} ${styles.linkedin}`}></div>
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
